// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {provider} from '../models';
import {match} from '../models';
import {config} from '../models';
import {verify} from '../models';

export function ApplyRename(arg1:string,arg2:Array<media.Op>):Promise<media.Result>;

export function AutoMatch(arg1:Array<media.File>,arg2:Array<provider.Episode>):Promise<Array<match.Pair>>;

export function ClearHistory():Promise<void>;

export function ComputeChecksum(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function ListEpisodes(arg1:string,arg2:string):Promise<Array<provider.Episode>>;

export function ListHistory():Promise<Array<media.HistoryEntry>>;

export function ListPresets():Promise<Array<media.Preset>>;

export function ListProviders():Promise<Array<provider.Info>>;

export function OpenDirectoryDialog():Promise<string>;

export function PreviewMatched(arg1:string,arg2:Array<media.File>,arg3:Array<provider.Episode>,arg4:Array<match.Pair>,arg5:provider.Show):Promise<Array<media.Op>>;

export function PreviewRename(arg1:string,arg2:Array<string>,arg3:Array<provider.Episode>,arg4:provider.Show):Promise<Array<media.Op>>;

export function RenderNamePreview(arg1:media.File,arg2:provider.Episode,arg3:provider.Show):Promise<string>;

export function RenderTemplatePreview(arg1:string,arg2:media.File,arg3:provider.Episode,arg4:provider.Show):Promise<string>;

export function RevertHistory(arg1:string):Promise<media.Result>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanDirectory(arg1:string):Promise<Array<media.File>>;

export function ScanDirectoryWithOptions(arg1:string,arg2:boolean,arg3:number):Promise<Array<media.File>>;

export function SearchShows(arg1:string,arg2:string):Promise<Array<provider.Show>>;

export function UndoLastRename():Promise<media.Result>;

export function VerifyEmbeddedCRC(arg1:string):Promise<verify.Result>;
