// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilesInDirectoryHandlerGO(arg1) {
  return window['go']['main']['App']['FilesInDirectoryHandlerGO'](arg1);
}

export function GetEpisodesGO(arg1) {
  return window['go']['main']['App']['GetEpisodesGO'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function RenameAllGO(arg1) {
  return window['go']['main']['App']['RenameAllGO'](arg1);
}

export function RenameSelectedGO(arg1, arg2) {
  return window['go']['main']['App']['RenameSelectedGO'](arg1, arg2);
}

export function SearchShow(arg1, arg2) {
  return window['go']['main']['App']['SearchShow'](arg1, arg2);
}
