// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {config} from '../models';
import {provider} from '../models';

export function ApplyRename(arg1:string,arg2:Array<media.Op>):Promise<media.Result>;

export function GetConfig():Promise<config.Config>;

export function ListEpisodes(arg1:string,arg2:string):Promise<Array<provider.Episode>>;

export function ListProviders():Promise<Array<provider.Info>>;

export function OpenDirectoryDialog():Promise<string>;

export function PreviewRename(arg1:string,arg2:Array<string>,arg3:Array<provider.Episode>,arg4:provider.Show):Promise<Array<media.Op>>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanDirectory(arg1:string):Promise<Array<media.File>>;

export function SearchShows(arg1:string,arg2:string):Promise<Array<provider.Show>>;

export function UndoLastRename():Promise<media.Result>;
