// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilesInDirectoryHandler(arg1:string):Promise<Array<string>>;

export function GetEpisodes(arg1:number):Promise<Array<string>>;

export function JsPrintLn(arg1:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function RenameAll():Promise<void>;

export function SearchShow(arg1:string):Promise<Array<string>>;
