// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilesInDirectoryHandler(arg1) {
  return window['go']['main']['App']['FilesInDirectoryHandler'](arg1);
}

export function GetEpisodes(arg1) {
  return window['go']['main']['App']['GetEpisodes'](arg1);
}

export function JsPrintLn(arg1) {
  return window['go']['main']['App']['JsPrintLn'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function RenameAll(arg1) {
  return window['go']['main']['App']['RenameAll'](arg1);
}

export function RenameSelected(arg1, arg2) {
  return window['go']['main']['App']['RenameSelected'](arg1, arg2);
}

export function SearchShow(arg1) {
  return window['go']['main']['App']['SearchShow'](arg1);
}
